// Next Js Components
import Head from "next/head";

//  Bootstrap Components
import Container from "react-bootstrap/Container";
import Row from "react-bootstrap/Row";
import Col from "react-bootstrap/Col";

import Button from "react-bootstrap/Button";

// Our Components
import ComponentLibraries from "./api/components/ComponentLibrariesList";

export default function Home() {
  return (
    <>
      <Head>
        <title>Bootstrap Example</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
        <main>
          <Container>
            <h1>Here's our simple bootstrap example</h1>
            <Row>
              <Col>
                <h4>Avaliable Component Libraries</h4>
                <ComponentLibraries/>
              </Col>

              <Col>
                <Button>Example Button</Button>
              </Col>
            </Row>
          </Container>
          
        </main>
      
    </>
  );
}
