import Head from "next/head";

// Material UI Import
import { Container } from "@mui/material";
import { Box } from "@mui/material";
import { Typography } from "@mui/material";


export default function Home() {
  return (
    <>
      <Head>
        <title>MUI Example</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container maxWidth="sm">
          <Box sx={{ my: 4 }}>

            <Typography variant="h2" component="h2">
              MUI looks good.
            </Typography>

            <Typography variant="p" component="p">
              You can perhaps see why this is a popular package.
            </Typography> 

          </Box>
        </Container>
      </main>

    </>
  );
}
