import Head from "next/head";

// MUI IMports
import { Container}  from "@mui/material";

// My own components
import ToDoList from "./components/todolist";

export default function Home() {
  return (
    <>
      <Head>
        <title>State Example</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
        <main>
          <Container>
            <ToDoList/>
          </Container>
          
        </main>
      
    </>
  );
}
