// State import
import { useState } from 'react'

// Data import
import { MOVIE_LIST } from '../utils/movies'

// Next.js import
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

// MUI components
import Alert from '@mui/material/Alert';
import Button from '@mui/material/Button';
import Container from '@mui/material/Container';
import Grid from '@mui/material/Grid';
import TextField from '@mui/material/TextField';
import Typography from '@mui/material/Typography';

import List from '@mui/material/List';
import ListItem from '@mui/material/ListItem';
import ListItemText from '@mui/material/ListItemText';

export default function Home() {

  const [search, setSearch] = useState("")
  const [year, setYear] = useState("")

  const [movies, setMovies] = useState(MOVIE_LIST)

  const handleSubmit = (event) => {
    event.preventDefault()
    console.log(`year: ${year}`)
    console.log(`search: ${search}`)

    filterMovies()
  }

  const filterMovies = () => {
    // Copy the movie list so w don't mutate the original data
    const filteredMovies =[...MOVIE_LIST]

    // Trim the Search inputs and check if theres a title value
    if (search.trim()) {
      // Filter the array for titles that include the serach as a substring
      filteredMovies = filteredMovies.filter((movie) => {
        return movie.name.toLowerCase().includes(search.trim().toLowerCase())
      })
    }

    // Trim the Search inputs and check if theres a year value
    if (year.trim()){
      // loop through the movies and check if the year is the same as the 
      filteredMovies = filteredMovies.filter((movie)=> {
       return movie.year === parseInt(year.trim())
      })  
    }

    setMovies(filteredMovies)
  }

  return (
    <div>
      <Head>
        <title>Our Movie App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700&display=swap"
        />
      </Head>

      <main>
        <Container sx={{color: 'text.secondary'}}>
          <Typography variant="h2" component="h2" style={{textAlign: "center"}}>
            Movies
          </Typography>
          <form style={{width: '100%'}} onSubmit={handleSubmit}>
            <Grid container spacing={2}>

              {/* This is the old MUI Grid format, because we are pinning package versions in this starter,
              in the new format you eould simply use size={6} instead*/}

              <Grid item xs={6}>
                <TextField
                  id="search-field"
                  label="search..."
                  variant="standard"
                  sx={{width: '100%'}}
                  onChange={(e)=> {setSearch(e.target.value)}}
                  value={search}
                  
                />
              </Grid>
              <Grid item xs={4}>
                <TextField
                  id="year-field"
                  label="year"
                  variant="standard"
                  sx={{width: '100%'}}
                  onChange={(e)=> {setYear(e.target.value)}}
                  value={year}
                />
              </Grid>
              <Grid item xs={2}>
                <Button
                  type="submit"
                  variant="contained"
                  sx={{bgcolor: 'warning.main', 
                    '&:hover': {
                      bgcolor: 'warning.dark', // Background color on hover
                    }}}
                >Filter</Button>
              </Grid>
              <Grid item xs={10}>
                {/* Add the error message here*/}
              </Grid>
            </Grid>
          </form>
          {movies.length === 0 &&
              <ListItem>
                <ListItemText>
                <Typography variant="p" component="div">
                  No results please search again.
                </Typography>
                </ListItemText>
              </ListItem>
            }
          <List sx={{width: `100%`}}>
          { movies.map((movieData, index)=> {
              return <ListItem key={index}>
                <ListItemText>
                  <Typography variant="p" component="div">
                    {movieData.name} ({movieData.year})
                  </Typography>
                </ListItemText>
              </ListItem>
            })
          }
          </List>

        </Container>
      </main>
    </div>
  )
}
